### PR TITLE
Create run_ms2deepscore_model_according_to_paper

### PR DESCRIPTION
**Pull request by niekdejonge**
@florian-huber 
The tutorial on MS2Deepscore is a bit outdated. 
It uses different model structure compared to the model in the paper and does not use validation data in the training. 
A student in our group is working with training MS2Deepscore models now, so this might be a good incentive to update this. :) 

The file I added is what I used to train the most recent MS2Deepscore model. Could you check if these settings are indeed correct? In that case we can maybe clean up this code a bit and add explanation and integrate this with the tutorial.

Let me know what you think.

### CODE REVIEW

**Comment by niekdejonge** [comment]
In #59 you mention a problem with early stopping, maybe we can implement this right away as well

**Comment by florian-huber** [comment]
As we just discussed, I would leave the early_stopping issue out for now (#59) because that will be a bit of work to implement.

**Comment by niekdejonge** [comment]
When going over the settings I noticed a few settings that I would like to double check:
- Using DataGeneratorAllInchikeys (instead of DataGeneratorAllSpectrums
- Setting allowed_missing_percentage to 100%. Otherwise the spectrum binning of the validation spectra does not work. I believe that having 0 peaks in known bins will always result in an embedding of only zeroes, so this is not a big problem. Also raising an error later, if one spectrum does not fit in is often not wanted behavior.
- I run model.model.fit. In this way the history is stored. However, in the original tutorial model.fit() was run. Is model.model.fit correct?

**Comment by niekdejonge** [comment]
I think I found a solution for the early stopping not saving the best model. Just adding the parameter restore_best_weights=True to the early stopping. (maybe you already suggested this during our meeting) However, I do not really know how to test if this works as expected. 
Checkpointer will still have the problem that it does not store the spectrum binning settings, since it uses the original keras save options. So I think the best solution is using early stopping but no checkpointer.

**Comment by florian-huber** [comment]
> * Using DataGeneratorAllInchikeys (instead of DataGeneratorAllSpectrums
> 

Yes, that's correct!
> * Setting allowed_missing_percentage to 100%. Otherwise the spectrum binning of the validation spectra does not work. I believe that having 0 peaks in known bins will always result in an embedding of only zeroes, so this is not a big problem. Also raising an error later, if one spectrum does not fit in is often not wanted behavior.
> 

Fine as well.
> * I run model.model.fit. In this way the history is stored. However, in the original tutorial model.fit() was run. Is model.model.fit correct?

Regarding the training itself, both will underneath call exactle the same function. The only difference is that the first returns the history, while the second option doesn't (we might change that if possible).

**Pull request merged**
